version: '3.3'

services:
  tests:
    build:
      context: .
      dockerfile: api-test.dockerfile
    command: npm run test:api
    depends_on:
      - api
      - mongo
    links:
      - mongo
      - api
    env_file:
      - .env
    environment:
      - API_URL=http://api:5000
      - MONGODB_URL=mongodb+srv://doadmin:0392eR5oP86jtM1B@db-mongodb-nyc3-33591-340c1998.mongo.ondigitalocean.com
    volumes:
      - type: volume
        source: servicesTest
        target: /usr/src/app/src/api/services/__test
        volume:
          nocopy: true

  api:
    build:
      context: .
      dockerfile: api-test.dockerfile
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - .env
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb+srv://doadmin:0392eR5oP86jtM1B@db-mongodb-nyc3-33591-340c1998.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=db-mongodb-nyc3-33591
      - DEBUG_CRM_SIGNUP=true
      - MAIL_DEBUG=true
    volumes:
      - type: volume
        source: servicesTest
        target: /usr/src/app/src/api/services/__test
        volume:
          nocopy: true

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=doadmin
      - MONGO_INITDB_ROOT_PASSWORD=0392eR5oP86jtM1B
    logging:
        driver: none

volumes:
  servicesTest:
