version: '3.3'

services:
  webpack:
    build: .
    command: npm run start:webpack
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./public/dist:/usr/src/app/public/dist:cached

  seed:
    build: .
    command: npm run seed
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - MONGODB_URL=mongodb+srv://doadmin:0392eR5oP86jtM1B@db-mongodb-nyc3-33591-340c1998.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=db-mongodb-nyc3-33591
    env_file:
      - .env

  api:
    build: .
    command: npm run start:api
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb+srv://doadmin:0392eR5oP86jtM1B@db-mongodb-nyc3-33591-340c1998.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=db-mongodb-nyc3-33591
      - SEED_LOCALHOST_CAMPAIGN=true
      - DEBUG_CRM_SIGNUP=true
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./public/dist:/usr/src/app/public/dist:cached

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=doadmin
      - MONGO_INITDB_ROOT_PASSWORD=0392eR5oP86jtM1B
    logging:
        driver: none
