version: '3.3'

services:
  webpack:
    build: .
    command: npm run start:webpack
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./public/dist:/usr/src/app/public/dist:cached

  seed:
    build: .
    command: npm run seed
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - MONGODB_URL=mongodb+srv://lucianorabu:hLJkLwY8CrXpPtRc@cluster0.yzeergf.mongodb.net/?retryWrites=true&w=majority
    env_file:
      - .env

  api:
    build: .
    command: npm run start:api
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "5665:5665"
    environment:
      - PORT=5665
      - MONGODB_URL=mongodb+srv://lucianorabu:hLJkLwY8CrXpPtRc@cluster0.yzeergf.mongodb.net/?retryWrites=true&w=majority
      - SEED_LOCALHOST_CAMPAIGN=true
      - DEBUG_CRM_SIGNUP=true
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./public/dist:/usr/src/app/public/dist:cached

  mongo:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lucianorabu
      - MONGO_INITDB_ROOT_PASSWORD=hLJkLwY8CrXpPtRc
    logging:
        driver: none
